### PR TITLE
Fix calling system functions without parentheses

### LINKED ISSUE #1223: Bug: "Formatting of macro call failed: paren_group not found."
Using current `master` (verible-v0.0-1959-gd9b88c73).

**Test case**

```systemverilog
module stop_time;
  initial begin
    #100.0us;
    $stop;
  end
endmodule
```

**Actual output**

```
tree_unwrapper.cc:2052] Formatting of macro call failed: paren_group not found.
*** Please file a bug. ***
```

### LINKED ISSUE #1247: tree-unwrapper: paren_group not found situation detected
**Test case**

```systemverilog
module foo ();
  $display($some_systemfunction);
endmodule
```

Formatting produces a result, but also complains about **formatting of macro call failed: paren_group not found**:

```
 echo 'module foo ();$display($some_systemfunction);endmodule' | bazel-bin/verilog/tools/formatter/verible-verilog-format -
E20220303 15:47:49.190407 1964513 tree_unwrapper.cc:2061] formatting of macro call failed: paren_group not found.
*** Please file a bug. ***
E20220303 15:47:49.192584 1964513 tree_unwrapper.cc:2061] formatting of macro call failed: paren_group not found.
*** Please file a bug. ***
module foo ();
  $display($some_systemfunction);
endmodule

```

### LINKED ISSUE #1280: Error message is printed when formatting assertion with $fatal
**Test case**

The following valid system verilog code results in the formatter printing and error message and suggesting I file a report.  If I remove the `$fatal` line of code the formatter runs without error.

```bash
v0.0-2008-gbbd498f0
Commit  2022-03-13
Built   2022-03-14T07:43:22Z
```

```systemverilog
module decimate_channel(
    input logic aclk,
    input logic tvalid,
    input logic tready
) ;

    assert property (@(posedge aclk) tvalid |-> tready)
    else begin
        $error("Error Messages");
        $fatal;
    end

endmodule    
```

I'm using the default options, see below for the command that I used

**Actual output**

```bash
$ verible-verilog-format bug2.sv
E20220322 14:24:23.078382 2187218 tree_unwrapper.cc:2061] formatting of macro call failed: paren_group not found.
*** Please file a bug. ***
E20220322 14:24:23.082552 2187218 tree_unwrapper.cc:2061] formatting of macro call failed: paren_group not found.
*** Please file a bug. ***
module decimate_channel (
    input logic aclk,
    input logic tvalid,
    input logic tready
);

  assert property (@(posedge aclk) tvalid |-> tready)
  else begin
    $error("Error Messages");
    $fatal;
  end

endmodule
```

**Expected or suggested output**
I would expect the output to be error free

### LINKED ISSUE #1392: viable-verilog-format error: formatting of macro call failed: paren_group not found.
A series of the following errors is reported for the code included below. The code is still correct after formating.
```
E20220813 17:01:59.735659  3304 tree_unwrapper.cc:2066] formatting of macro call failed: paren_group not found.
*** Please file a bug. ***
E20220813 17:01:59.736397  3304 tree_unwrapper.cc:2066] formatting of macro call failed: paren_group not found.
*** Please file a bug. ***
E20220813 17:01:59.736429  3304 tree_unwrapper.cc:2066] formatting of macro call failed: paren_group not found.
*** Please file a bug. ***
E20220813 17:01:59.736505  3304 tree_unwrapper.cc:2066] formatting of macro call failed: paren_group not found.
*** Please file a bug. ***
E20220813 17:01:59.739161  3304 tree_unwrapper.cc:2066] formatting of macro call failed: paren_group not found.
*** Please file a bug. ***
E20220813 17:01:59.739279  3304 tree_unwrapper.cc:2066] formatting of macro call failed: paren_group not found.
*** Please file a bug. ***
E20220813 17:01:59.739307  3304 tree_unwrapper.cc:2066] formatting of macro call failed: paren_group not found.
*** Please file a bug. ***
E20220813 17:01:59.739377  3304 tree_unwrapper.cc:2066] formatting of macro call failed: paren_group not found.
*** Please file a bug. ***
```
Best,
Robert
```
$> cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
```
```
$> uname -a
Linux local 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
```
$> verible-verilog-syntax --version
v0.0-2188-g1c92d70d
Commit	2022-08-12 16:28:49 -0700
Built	2022-08-13T00:00:16Z
```
```systemverilog
module top_module_tb();

  bit clk;
  bit rst_n;
  bit store;
  bit restore;
  bit data_in;
  wire data_out;
  wire frame_start;

top_module dut(.*);

//------------------------------------------------------------------------------
  int expected[$];

//------------------------------------------------------------------------------
  initial begin : clock
    clk = 0;
    forever begin
      #50ns clk = ~clk;
    end
  end

//------------------------------------------------------------------------------
  task reset();
    rst_n = '1;
    @(negedge clk) rst_n = '0;
    @(negedge clk) rst_n = '1;
  endtask

//------------------------------------------------------------------------------
  task send_serial_16_msb_first(
    input logic [15:0] data
  );
    @(posedge clk);
    for(int i = 15; i >= 0; i--) begin
      @(negedge clk) data_in = data[i];
    end

  endtask

//------------------------------------------------------------------------------
  task send_a_b(
    input logic [15:0] a,
    input logic [15:0] b
  );
    $display("%0t send_a_b(%0d, %0d)",$time,a,b);
    send_serial_16_msb_first(b);
    send_serial_16_msb_first(a);
    @(negedge clk) data_in = '0;
    store = '1;
    @(negedge clk) store = '0;
    expected.push_back(a*b);
  endtask

//------------------------------------------------------------------------------
  logic [31:0] result_reg;
  logic [31:0] expected_reg;
  always @(negedge clk) begin : store_result
    if(frame_start) begin
      for(int i = 31; i >= 0; i--) begin
        result_reg[i] = data_out;
        @(negedge clk);
      end
      expected_reg = expected.pop_front();
      assert(result_reg == expected_reg )begin
        $display("%0t Result OK: %0d", $time, result_reg);
      end 
      else begin
        $warning("%0t Result BAD: expected %0d, received :%0d", $time, expected_reg, result_reg);
      end
    end
  end

//------------------------------------------------------------------------------
  initial begin : MAIN
    reset();
    send_a_b(7,8);
    send_a_b(128,256);
    repeat(10) send_a_b($random, $random);

    repeat(40) @(negedge clk);
    $finish;
  end

endmodule
```

### PR DESCRIPTION
**Pull request by msierszulski**
This commit removes the error message when formatting system functions without parentheses, because they are formatted well after all.

Fixes #1280,
Fixes #1223,
Fixes #1247,
Fixes #1392.

### CODE REVIEW

File: verilog/formatting/tree_unwrapper.cc [hunk 1]
```diff
@@ -2060,8 +2060,9 @@ class MacroCallReshaper {
 
     paren_group_ = FindDirectChild(main_node_,
                                    OriginTagIs{NodeTag(NodeEnum::kParenGroup)});
+
+    // Macro can be used without parentheses
     if (!paren_group_) {
-      LOG_PARTITION_BUG("paren_group not found.");
```
Comment (hzeller) [inline verilog/formatting/tree_unwrapper.cc:2064]: This message has been first added in https://github.com/chipsalliance/verible/commit/56600a7ed5125a56b9ee9f0c5a5995bfa4366996 so maybe @mglb can comment on the reason for it, and maybe if it is ok in this case.

**Comment by hzeller** [comment]
Can you also add a formatter unit test that covers this particular case ?

File: verilog/formatting/tree_unwrapper.cc (hunk 1 above)
Comment (mglb) [reply verilog/formatting/tree_unwrapper.cc:2064]: It is OK, this was a wrong assumption.

**Comment by msierszulski** [comment]
@hzeller I added a test to check the use case of system functions without parentheses. Can you take a look at it?

**Review by hzeller — APPROVED** [review]
Nice!
