### PR TITLE
Fixed diagnostics for already existing symbol

### LINKED ISSUE #1654: Multiple defined symbol crashes language server
A couple of questions first

 - Your IDE/editor (e.g. vscode, emacs,...) you use with verible LSP ? VSCode
 - IDE version: 1.74.3
 - What other SystemVerilog plugins are active alongside ? No
-----

**What activity failed**
go-to-definition fails when there are two files in the file list that define the same symbol.

**Expectation**
At least the jump to one definition without crashing.
**Ideal** scenario: show that there are multiple definitions and allow user to choose where to go.

**What actually happened**
```
I0130 11:22:03.951129 2859273 symbol-table-handler.cc:78] Parsing project files...
I0130 11:22:03.951231 2859273 verilog_project.cc:81] Analyzed /home/hzeller/double-def/another-bar.sv in 77.406us
I0130 11:22:03.951283 2859273 verilog_project.cc:81] Analyzed /home/hzeller/double-def/bar.sv in 21.2us
F0130 11:22:03.951314 2859273 text_structure.cc:153] Check failed: to <= static_cast<int>(Contents().length()) (4106 vs. 37) "bar"
*** Check failure stack trace: ***
    @     0x560c56b63189  absl::log_internal::LogMessage::SendToLog()
    @     0x560c56b635f9  absl::log_internal::LogMessageFatal::~LogMessageFatal()
    @     0x560c56b00566  verible::TextStructureView::GetRangeForText()
    @     0x560c569e1c40  verilog::SymbolTable::Builder::DiagnoseSymbolAlreadyExists()
    @     0x560c569e6aad  verilog::SymbolTable::Builder::EmplaceElementInCurrentScope()
    @     0x560c569e6ae6  verilog::SymbolTable::Builder::DeclareScopedElementAndDescend()
    @     0x560c569ec578  verilog::SymbolTable::Builder::Visit()
    @     0x560c56b3e921  verible::TreeContextVisitor::Visit()
    @     0x560c569ec15b  verilog::SymbolTable::Builder::Visit()
    @     0x560c569e5f9b  verilog::BuildSymbolTable()
    @     0x560c569e60a9  verilog::ParseFileAndBuildSymbolTable()
    @     0x560c569e63cb  verilog::SymbolTable::Build()
    @     0x560c569a67e2  verilog::SymbolTableHandler::BuildProjectSymbolTable()
    @     0x560c569df9d3  verilog::SymbolTableHandler::FindDefinition()
    @     0x560c569ddb92  std::_Function_handler<>::_M_invoke()
    @     0x560c56b5ca38  verible::lsp::JsonRpcDispatcher::CallRequestHandler()
    @     0x560c56b5d1ce  verible::lsp::JsonRpcDispatcher::DispatchMessage()
    @     0x560c56b5d4db  verible::lsp::MessageStreamSplitter::ProcessContainedMessages()
    @     0x560c56b5da06  verible::lsp::MessageStreamSplitter::ReadInput()
    @     0x560c56b5db08  verible::lsp::MessageStreamSplitter::PullFrom()
    @     0x560c569d368d  verilog::VerilogLanguageServer::Run()
    @     0x560c569c7db3  main
    @     0x7f6c20d6718a  (unknown)
[Info  - 11:22:04 AM] Connection to server got closed. Server will restart.
[Error - 11:22:04 AM] Request textDocument/definition failed.
```
**Test case**

Two files, that both define a symbol `bar`

`bar.sv`
```systemverilog
module bar();
  // one bar
endmodule
```

`another-bar.sv`
```systemverilog
module bar();
  // another bar
endmodule
```

... then a file that uses the symbol

`foo.sv`
```systemverilog
module foo();
  bar x;
endmodule
```

File list created with
```bash
echo *.sv > verible.filelist
```

Bug is triggered when opening `foo.sv`, then placing cursor on `bar` and request `Go To Definition`.

### PR DESCRIPTION
**Pull request by glatosinski**
Fixes #1654 

SymbolTable during build has a pointer to currently processed source and string view to symbol.

When symbol is redefined in another file, the source pointer is no longer valid and resolving the location of the previous symbol in the current file was resulting in assertion error.

This commit uses the file_origin from SymbolTableNode for previous symbol to provide symbol location.

The current behaviour is that we keep the first observed definition of the symbol, while returning error in diagnostics for other redefinitions.

### CODE REVIEW

**Comment by hzeller** [comment]
Filed #1663 for the CI hickup investigation.

**Comment by hzeller** [comment]
The CI issue is resolved, so if you rebase, that should work again.

In addition to the e2e verilog-language-server_test, can you also add a test in `symbol-table_test.cc` that fails before and is fixed after ? That way isolated work on the symbol-table.cc will be possible just with running the corresponding test.

File: verilog/analysis/symbol_table.cc [hunk 1]
```diff
@@ -1204,12 +1204,14 @@ class SymbolTable::Builder : public TreeContextVisitor {
   }
 
   void DiagnoseSymbolAlreadyExists(absl::string_view name,
-                                   absl::string_view previous) {
+                                   const SymbolTableNode* previous_symbol) {
```
Comment (hzeller) [inline verilog/analysis/symbol_table.cc:1207]: Since the `previous_symbol` can not be null (at least it looks like there is no test for it in this function), could we make it a const reference `const SymbolTableNode& previous_symbol` ?

**Review by hzeller — COMMENTED** [review]
Nice!
Can you also add a tess tin `symbol_table_test.cc` to verify that it is fixed if just that test would be run ?

File: verilog/tools/ls/verilog-language-server_test.cc [hunk 2]
```diff
@@ -1046,6 +1046,57 @@ TEST_F(VerilogLanguageServerSymbolTableTest,
   ASSERT_EQ(response_b["result"][0]["uri"], "file://" + module_a.filename());
 }
 
+TEST_F(VerilogLanguageServerSymbolTableTest, MultipleDefinitionsOfSameSymbol) {
+  const absl::string_view filelist_content = "bar_1.sv\nbar_2.sv\nfoo.sv";
+
+  const absl::string_view  //
```
Comment (hzeller) [inline verilog/tools/ls/verilog-language-server_test.cc:1052]: Why are the others `static constexpr` and this one just `const` ?

Comment (glatosinski) [reply verilog/tools/ls/verilog-language-server_test.cc]: Fixed

**Review by hzeller — APPROVED** [review]
LGTM, thanks!

Will merge when CI finishes.
