### PR TITLE
Removed CentOS 8 release as it is EOL

### LINKED ISSUE #1165: CentOS8 docker build starting to fail
https://github.com/chipsalliance/verible/runs/5013790643

Looks like it can't download from a URL for a repo. This might either be a temporary glitch on that server or a changed URL in general that requires to update the docker to have the URLs it uses point to the right one.

### PR DESCRIPTION
**Pull request by corco**
CentOS 8 is EOL and fails to build as a consequence

Closes #1165

### CODE REVIEW

File: releasing/docker-run.sh [hunk 1]
```diff
@@ -72,8 +72,7 @@ case "$TARGET_OS" in
   ;;
   centos)
```
Comment (umarcor) [inline releasing/docker-run.sh:73]: Maybe it's worth adding a comment here explaining that CentOS 8 is EOL but CentOS 7 is "alive" until 2024. That will avoid us (others) wondering in the future why is an "older" version tested but not the "newer".

**Review by umarcor — APPROVED** [review]

File: releasing/docker-run.sh (hunk 1 above)
Comment (corco) [reply releasing/docker-run.sh:73]: I updated the releasing/README with that information

**Review by umarcor — APPROVED** [review]
